version: 2

sources:
  - name: raw_data
    schema: public
    tables:
      - name: eurostat_indicators

models:
  - name: test_eurostat
    description: "A test model for Eurostat data"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: test_eurobatometer
    description: "A test model for Eurobarometer data"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
