version: 2

sources:
  - name: eurostat
    schema: public
    tables:
      - name: eurostat_indicators
      - name: eurostat_bridge
      - name: eurostat_table_catalog

models:
  - name: eurostat_map_full
    description: "Full catalog of indicators and tables for Eurostat data."
    columns:
      - name: indicator_code
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
